backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "references"
    label: "Reference"
    folder: "src/data/references"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "reference"}
      - {label: "Jméno autora", name: "title", widget: "string"}
      - {label: "Pozice autora", name: "position", widget: "string"}
      - {label: "Název společnosti", name: "company", widget: "string"}
      - {label: "Popis společnosti", name: "description", widget: "string"}
      - {label: "Quote", name: "body", widget: "markdown"}
  - name: "about"
    label: "About"
    folder: "src/data/about"
    file: "src/data/about/about.md"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
      - {label: "Jméno", name: "name", widget: "string"}
      - {label: "Pozice", name: "position", widget: "string"}
      - {label: "Fotka", name: "image", widget: "image"}
      - {label: "Citát", name: "quote", widget: "text"}
      - {label: "Bio", name: "body", widget: "markdown"}